sudo: required
language: generic
services:
	- docker
	
before_install:
	- docker build -t prashy561/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true prashy561/docker-react npm run test
